### ISSUE TITLE
PDFStitcher alpha freezes with halla files (only during layers manipulation)

### ISSUE THREAD

**Issue by Triffen** [cfcurtis/pdfstitcher#33] opened 2021-03-07 11:34 UTC
Steps:
Open free Stardust A0 by Halla Patterns
Choose any operation on Layer tab (tried only coloring, coloring with changing line thickness, switching off layers)
Actual result: program is unresponsive or barely responsive, file never generated.
![image](https://user-images.githubusercontent.com/4696816/110238340-d0f52900-7f49-11eb-858c-6942af020f99.png)

**Comment by cfcurtis** [comment] 2021-03-07 20:30
Confirmed this is an issue, likely due to the size of the PDF. This pattern is 57 MB and just reading the content to start parsing layers sends my memory usage upwards of 3 GB. Addressing this bug is going to be tricky and might require refactoring to use bytestreams instead of pikepdf.parse_content_stream.

**Comment by mara004** [comment] 2021-05-20 12:59
Until this is resolved, should we maybe prevent processing very large PDFs, or at least issue a warning?
How would using bytestreams look like? Does it mean to analyse the content stream without pikepdf?

**Comment by mara004** [comment] 2021-06-17 14:15
Should we maybe prevent processing very large PDFs, or at least issue a warning (until this is resolved)?
With using bytestreams you probably mean [this](https://pikepdf.readthedocs.io/en/latest/topics/streams.html#reading-stream-objects-as-a-python-i-o-streams), right?

**Comment by cfcurtis** [comment] 2021-06-19 20:48
> Should we maybe prevent processing very large PDFs, or at least issue a warning (until this is resolved)?
> With using bytestreams you probably mean [this](https://pikepdf.readthedocs.io/en/latest/topics/streams.html#reading-stream-objects-as-a-python-i-o-streams), right?

A warning might be a good idea, maybe a threshold of 10 MB or so? In general I'm not too motivated to address this because it usually means that the lines aren't actually lines anyways, so layer modification doesn't do what it should.

I originally started parsing using read_raw_bytes and regex, but parse_content_stream seemed more reliable and was actually faster. It might have some memory advantages though that would help in the large file size situation.

**Comment by kimmellr** [comment] 2021-11-27 07:08
Check out this implementation of layer filtering.  It does not require any parsing of the pdf stream, and may improve the large file performance.

[pdflayers](https://github.com/SimonSegerblomRex/pdflayers)

**Comment by mara004** [comment] 2021-11-27 08:54
@kimmellr pdflayers only changes the on/off state of OCGs. It is not capable of actually removing layers (as necessary for working with Inkscape), nor can it modify line properties.
If you only want to turn layers off, it is possible to use the hide option - this will avoid parsing the stream.

**Comment by cfcurtis** [comment] 2022-04-22 23:12
With improvements to pikepdf/pikepdf, this doesn't seem to be nearly as much of an issue. It is still slow, but I am able to process layers on a 58 GB pdf within about 8 minutes on a 7th gen Core i5. Memory usage crept up to 1.3 GB though, so there may be a leak somewhere. However, I'm closing this particular issue as I don't think it needs further attention from the pdfstitcher side.

**Closed by cfcurtis** 2022-04-22 23:12 UTC
Labels: bug, Specific pattern issue
