### ISSUE TITLE
After layers manipulation on Fathom 5 by Pollywoggles Inkscape can't ungroup

### ISSUE THREAD

**Issue by Triffen** [cfcurtis/pdfstitcher#108] opened 2021-07-29 20:47 UTC
Inkscape works fine with the original file. I've never seen this before, it 'ungroups' but it was one group, then two, then one again, then four, and so on.

I used free Fathom 5 by Pollywoggles: https://www.pollywoggles.ca/store/p56/Fathom_Five.html
Removed all layers except for 4, 6 and labels. Probably changed the color and the thickness for two size layers. The resulting file was 2-3 times bigger and Inkscape couldn't ungroup it and eventualy froze.

**Comment by cfcurtis** [comment] 2021-07-30 15:36
Thank you for the detailed report! Is this with v0.4.1 or v0.5-beta?

**Comment by Triffen** [comment] 2021-07-30 15:42
I knew I forgot something! It's a new 0.5 beta.

**Comment by cfcurtis** [comment] 2021-07-30 18:57
Okay, I think there were two issues here. The file size issue is a debug flag that I had enabled in saving the file, so I got rid of that. It's been around forever but this is the first report of it affecting things to that degree, so who knows what other files might be improved!

For Inkscape I was able to ungroup it by using the extension "Deep Ungroup" (Extensions -> Arrange -> Deep Ungroup). I'm not really sure how PDFStitcher could be introducing additional groups as it should just be stripping things away from the content stream without rearranging, but you never know. I'll keep this bug open for now.

**Comment by Triffen** [comment] 2021-07-31 10:37
I've seen the files gettings bigger from time to time but thought maybe it was undoing compression or something.
I've pulled and got a file a bit smaller than the original so that's good.
Deep Ungroup doesn't always work where Python 2 is deprecated, including in Debian :( Sometimes it works but mostly throws an error or freezes.

**Comment by mara004** [comment] 2021-08-05 19:15
> where Python 2 is deprecated, including in Debian

Which version of Debian? Python 2 is still included up to sid (Debian 12). If the issue is about symlinks defaulting to python3, you could install the python-is-python2 package, but this might break other software...

**Comment by Triffen** [comment] 2021-08-05 19:42
Current testing plus a bit of experimental, I don't follow the names. I definitely don't want other software to break ;)

**Comment by mara004** [comment] 2021-08-06 16:52
> I definitely don't want other software to break ;)

As long as you only use python software from the official repository, it should be risk-free since Debian > 10 and Ubuntu >= 20.04 now enforce the use of an explicit python target (python2 or python3, but not just python). If you use lots of newer third-party python software, it could cause issues, but as far as I know most developers explicitly target the python3 executable nowadays, so it shouldn't be that risky.

**Comment by cfcurtis** [comment] 2021-09-19 19:19
Closing issue as the group/ungroup thing is not controlled by PDFstitcher.

**Closed** 2021-09-19 19:19 UTC
